server:
  port: 7089

# 数据库和缓存配置
spring:
  redis:
      host: redis
      port: 6379
      timeout: 3000
      pool:
        max-idle: 100
        min-idle: 20
        max-active: 100
        max-wait: -1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/rainbow?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
